### PR TITLE
used the metadata service to determine NODE; make sure we are in clus…

### PR DESCRIPTION
**Pull request by cnelson**
Simplify the drain script / only attempt to drain if we are in the k8s cluster

@jmcarp

### CODE REVIEW

**Comment by jmcarp** [comment]
In theory, we want this release to work on non-AWS clouds, so I think we should avoid AWS-specific logic--there's an exception in https://github.com/18F/kubernetes-release/blob/master/jobs/kubernetes-minion/templates/pre-start.erb, but the goal is to deprecate that script when possible. WDYT?

Also, why would a node that's running the minion drain script not be in the cluster?

**Comment by cnelson** [comment]
I saw it happen today when testing updating stemcells, cluster got into a weird state drain scripts started blowing up -- check concourse for details.

**Comment by jmcarp** [comment]
Got it, checking if the node is part of the cluster sounds reasonable if it helps not die when the cluster is in a weird state.

**Comment by cnelson** [comment]
I'll open another PR with a different patch that doesn't rely on the metadata service (although which cloud providers don't support that at this point?) that adds some safety checks to the drain scripts once I can pin-point what caused it to fail when changing stemcell versions

**Comment by jmcarp** [comment]
Do all providers use the same metadata interface? I don't have a gcp account to mess with, but it looks like their urls are a little different, like http://metadata.google.internal/computeMetadata/v1/instance/attributes/hostname.

**Pull request closed without merging**
